export const CURRENT_WEATHER = 'CURRENT_WEATHER';
export const SEVEN_DAYS_WEATHER = 'SEVEN_DAYS_WEATHER';

export const SEVEN_DAYS_WEATHER_REQUEST = 'SEVEN_DAYS_WEATHER_REQUEST';
export const SEVEN_DAYS_WEATHER_SUCCESS = 'SEVEN_DAYS_WEATHER_SUCCESS';
export const SEVEN_DAYS_WEATHER_FAIL = 'SEVEN_DAYS_WEATHER_SUCCESS';